### ISSUE TITLE
Boards to purchase

### ISSUE THREAD

**Issue by AGTDesigns** [Kreeblah/SidewinderToUSBV2#1]
Hi! Do you still have boards to sell? I have a Sidewinder FFB Wheel with gameport that I would like to use with Win10, do you think it might work? How much would the board cost?
Thanks a lot!

**Comment by Kreeblah** [comment]
I do still have some to sell, yes.

This hardware should be completely compatible with the original design, so I'd imagine it works as well as it would on the original adaptor (working except for the force feedback functionality), but since I don't own an FFB Wheel, I don't really have the means to test it myself.

If you're still interested in one or if you have some more questions, feel free to send me an e-mail.  You can reach me via the same username as here at Gmail.
